#!/usr/bin/env php
<?php
if (!is_file('vendor/autoload.php')) {
	echo "\033[0;31mERROR:\033[0m\n\tPlease run \033[1;37m\033[41mcomposer install\033[0m first!\n";
	exit(1);
}

include __DIR__ . '/bootstrap.php';
@ob_end_clean();
// comand list
$commands                  = apply_filter('artisan\getCommands', []);
$commands['init']          = new \wulaphp\command\InitCommand();
$commands['create-module'] = new \wulaphp\command\CreateModuleCommand();
$commands['create-ext']    = new \wulaphp\command\CreateExtensionCommand();
$commands['create-table']  = new \wulaphp\command\CreateTableCommand();
$commands['help']          = new \wulaphp\artisan\ArtisanHelpCommand();

ksort($commands);

set_time_limit(0);
$cmd = isset($argv[1]) ? $argv[1] : 'help';

if (!isset($commands[ $cmd ])) {
	$commands['help']->help("Unkown Command: " . $cmd);
} else {
	exit($commands[ $cmd ]->run());
}